// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bg_black': string;
  'bg_cyan_4': string;
  'bg_cyan_8': string;
  'bg_cyan_base': string;
  'bg_error': string;
  'bg_pink_base': string;
  'bg_purple_base': string;
  'bg_success': string;
  'bg_volcano_base': string;
  'bg_warning': string;
}
export const cssExports: CssExports;
export default cssExports;
