// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  color_black: string;
  color_cyan_4: string;
  color_cyan_8: string;
  color_cyan_base: string;
  color_error: string;
  color_pink_base: string;
  color_purple_base: string;
  color_success: string;
  color_volcano_base: string;
  color_warning: string;
}
export const cssExports: CssExports;
export default cssExports;
